//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClient
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Screen { get; set; }
        public string Product { get; set; }
        public string Company { get; set; }
        public string Message { get; set; }
        public string Agent { get; set; }
        public string Status { get; set; }
        public string Source { get; set; }
        public string IP { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    }
}
